### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by RobertBColton**
A few small changes to make the README a little cleaner and to show the emoticons. I did this by hand because Inkscape was obfuscating the diff. I can't for the life of me get GitHub's CDN to purge the SVGs though.

### CODE REVIEW

**Comment by JoshDreamland** [comment]
This is an extremely noisy change... Are any of those width/height values actually used, or can they be deleted instead?

**Comment by RobertBColton** [comment]
You should have seen the obfuscation that Inkscape created when I used its automatic fit canvas to elements. I'll give it a try and let you know.

**Comment by JoshDreamland** [comment]
I'm not suggesting you screwed something up. InkScape seems to think it's a good idea to assign width and height attributes to use objects, which don't seem to be using those. I'm asking what happens if you just remove the lines you're changing, rather than updating them all to 800×600. My guess is it'll still be fine.

**Comment by RobertBColton** [comment]
Thanks for pointing that out, commit amended. The icons seem to be rendering fine without those widths and heights. I opened in Firefox, Chrome, IE, Edge, and Inkscape. Renders fine in all of them. One thing I should mention is that removing the width and the height from the root SVG node causes them to always render 100% width and 100% height (in my browsers anyway). Is that undesirable? I don't know if the transforms could also be removed? Should I bother to test?

**Comment by JoshDreamland** [comment]
Excellent—this should greatly cut down on noise in future changes. Thank you for filtering that garbage out.

**Pull request merged**
